# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('number', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('detail', models.CharField(max_length=128)),
                ('count', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
    ]
